apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only
subjects:
- kind: ServiceAccount
  name: read-only
  namespace: scc-project
roleRef:
  kind: Role
  name: read-only
  apiGroup: rbac.authorization.k8s.io
