apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: scc-project
  name: read-only
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - read-only
