apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helper-view
  namespace: rbac-project
subjects:
- kind: ServiceAccount
  name: helper
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

